### ISSUE TITLE
[feature request] typescript support.

### ISSUE THREAD

**Issue by LeuisKen** [vireshshah/custom-protocol-check#1]
It will be nice to have a d.ts file for types, of rewrite this little repo to typescript.

If you agree, I'd love to make a pull request to make this repo to typescript.

Thank you,

: )

**Comment by vireshshah** [comment]
Sure. Please go ahead.

**Comment by webrsb** [comment]
I have added it. (#9)

**Comment by vireshshah** [comment]
Thanks @webrsb
