### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by NZainchkovskiy** [vireshshah/custom-protocol-check#4]
Hi!
Thank you for great work.
It's working in FireFox, but in Chrome it's always says that protocol not found, even for registered protocol. Windows 10, Chrome 80.
It is supposed to work with latest Chrome, or not?
Thank you!

**Comment by NZainchkovskiy** [comment]
Update - it's not working inside iframe. Without iframe it's works.

**Comment by vireshshah** [comment]
Yes, it won't work within iframe. Thanks!
