### ISSUE TITLE
1.1.0 contained breaking change

### ISSUE THREAD

**Issue by vpzomtrrfrt** [vireshshah/custom-protocol-check#5]
Minor versions are expected to be compatible with old code, but it seems that 1.1.0 introduced a parameter in the middle of the parameter list, causing the `unsupportedCb` to be treated as a timeout

**Comment by vireshshah** [comment]
@vpzomtrrfrt Apologies for that. I thought very few people might be using `unsupportedCb` parameter and `timeout` parameter was something many users were asking so thought to put ahead in params list. I agree, I could have bumped up major version.

Sorry for inconvenience.
